"""Public declarative Alertissimo DSL surface, validation, and lowering."""

from .capability_validation import (
    SurfaceCapabilityCheck,
    SurfaceCapabilityEvidence,
    SurfaceCapabilityReport,
    SurfaceCapabilityStatus,
    SurfaceCapabilityValidationError,
    validate_surface_capabilities,
)
from .lowering import (
    SurfaceCompilation,
    SurfaceLoweringError,
    compile_surface,
    compile_surface_to_ir,
    lower_surface,
    lower_surface_to_ir,
)
from .parser import grammar_text, parse_surface_script
from .surface import (
    AngularRadius,
    CandidateSet,
    DSLParseError,
    Duration,
    FilterClause,
    InsideClause,
    LatestClause,
    MatchClause,
    OrderByClause,
    RankedByClause,
    RequirementClause,
    SurfaceClause,
    SurfaceScript,
    WhereClause,
    WithinClause,
)
from .validation import (
    SemanticRecordReference,
    SurfaceValidationIssue,
    SurfaceValidationReport,
    ValidationSeverity,
    extract_semantic_record_references,
    resolve_record_type,
    validate_surface_semantics,
)

__all__ = (
    "AngularRadius",
    "CandidateSet",
    "DSLParseError",
    "Duration",
    "FilterClause",
    "InsideClause",
    "LatestClause",
    "MatchClause",
    "OrderByClause",
    "RankedByClause",
    "RequirementClause",
    "SemanticRecordReference",
    "SurfaceCapabilityCheck",
    "SurfaceCapabilityEvidence",
    "SurfaceCapabilityReport",
    "SurfaceCapabilityStatus",
    "SurfaceCapabilityValidationError",
    "SurfaceClause",
    "SurfaceCompilation",
    "SurfaceLoweringError",
    "SurfaceScript",
    "SurfaceValidationIssue",
    "SurfaceValidationReport",
    "ValidationSeverity",
    "WhereClause",
    "WithinClause",
    "compile_surface",
    "compile_surface_to_ir",
    "extract_semantic_record_references",
    "grammar_text",
    "lower_surface",
    "lower_surface_to_ir",
    "parse_surface_script",
    "resolve_record_type",
    "validate_surface_capabilities",
    "validate_surface_semantics",
)
