"""Offline end-to-end evaluation of 30 new English NLP -> DSL examples."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from time import monotonic
from urllib.error import URLError

from alertissimo.api import execute_dsl, validate_dsl
from evaluate_local_nlp import _generate
from scripts.smoke.executors import FixtureEndpointExecutor
from scripts.smoke.scenarios import _fixtures

HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE / "nlp_30_cases.jsonl"
DEFAULT_OUTPUT = HERE / "nlp_30_results.md"


def load_cases(path: Path) -> list[dict[str, str]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def run_case(case: dict[str, str], index: int, *, model: str, host: str) -> dict[str, object]:
    row: dict[str, object] = {"request": case["request"], "expected_dsl": case["expected_dsl"]}
    try:
        dsl, generation_seconds = _generate(
            host=host, model=model, user_text=case["request"], seed=42
        )
        row.update(dsl=dsl, generation_seconds=round(generation_seconds, 3))
    except (URLError, TimeoutError, KeyError, ValueError) as error:
        row.update(dsl="", generated=False, executed=False, error=f"model: {error}")
        return row
    row["generated"] = bool(dsl.strip())
    row["exact"] = dsl.rstrip() == case["expected_dsl"].rstrip()
    validation = validate_dsl(dsl, name=f"NLP 30 case {index}")
    row.update(valid=validation.is_valid, runnable=validation.is_runnable)
    if not validation.is_runnable:
        row["executed"] = False
        row["error"] = repr(validation.lowering_error or validation.parse_error)
        return row
    try:
        scenario = "dsl-pipeline" if "from lsst" in dsl.lower() else "dsl-multi-provider"
        executor = FixtureEndpointExecutor(_fixtures(scenario, ()))
        started = monotonic()
        execution = execute_dsl(dsl, name=f"NLP 30 case {index}", executor=executor)
        row.update(
            executed=all(step.state.value == "succeeded" for step in execution.run.steps),
            seconds=round(monotonic() - started, 3),
            steps=len(execution.run.steps),
            portfolios=len(execution.portfolios),
            calls=len(executor.calls),
        )
    except Exception as error:  # report every case, then continue the suite
        row.update(executed=False, error=f"{type(error).__name__}: {error}")
    return row


def render(rows: list[dict[str, object]], input_path: Path) -> str:
    total = len(rows)
    count = lambda key: sum(bool(row.get(key)) for row in rows)
    lines = [
        "# NLP → DSL 30-case end-to-end test",
        "",
        f"- Input: `{input_path.name}`",
        "- Translation: generated by the configured Ollama model; gold DSL is used only for exact-match comparison.",
        "- Execution: offline registered smoke fixtures; no provider network calls.",
        "",
        "| Metric | Result |",
        "|---|---:|",
        f"| NLP examples | {total}/30 |",
        f"| Model generated non-empty DSL | {count('generated')}/{total} |",
        f"| Exact gold DSL | {count('exact')}/{total} |",
        f"| Valid DSL | {count('valid')}/{total} |",
        f"| Runnable DSL | {count('runnable')}/{total} |",
        f"| Executed successfully | {count('executed')}/{total} |",
        "",
    ]
    for index, row in enumerate(rows, 1):
        lines += [f"## {index}", "", f"> {row['request']}", "", "```dsl", str(row["dsl"]), "```", ""]
        lines += [
            f"- valid: {'yes' if row.get('valid') else 'no'}",
            f"- generated: {'yes' if row.get('generated') else 'no'}",
            f"- exact gold match: {'yes' if row.get('exact') else 'no'}",
            f"- runnable: {'yes' if row.get('runnable') else 'no'}",
            f"- executed: {'yes' if row.get('executed') else 'no'}",
        ]
        if row.get("error"):
            lines.append(f"- error: `{row['error']}`")
        elif row.get("seconds") is not None:
            lines.append(f"- steps: {row['steps']}; portfolios: {row['portfolios']}; fixture calls: {row['calls']}; execution: {row['seconds']} s")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--model", default="alertissimo-qwen3-qlora:latest")
    parser.add_argument("--host", default="http://127.0.0.1:11434")
    args = parser.parse_args()
    cases = load_cases(args.input)
    if len(cases) != 30:
        raise SystemExit(f"expected exactly 30 cases, found {len(cases)}")
    rows = [
        run_case(case, index, model=args.model, host=args.host)
        for index, case in enumerate(cases, 1)
    ]
    args.output.write_text(render(rows, args.input), encoding="utf-8")
    print(f"{sum(bool(row.get('valid')) for row in rows)}/30 valid; {sum(bool(row.get('executed')) for row in rows)}/30 executed")
    print(args.output)
    return 0 if all(row.get("generated") and row.get("valid") and row.get("executed") for row in rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
