"""Strongly typed IDs for data owned by Alertissimo.

These IDs are deliberately independent from executor implementation classes.
They identify non-semantic data carried through later pipeline stages.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import uuid4


@dataclass(frozen=True)
class _InternalId:
    value: str

    def __post_init__(self) -> None:
        if not isinstance(self.value, str) or not self.value:
            raise ValueError("internal ID value must be a non-empty string")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True)
class InternalPortfolioId(_InternalId):
    """Alertissimo identity for a portfolio (generated by Portfolio Core)."""


@dataclass(frozen=True)
class InternalRecordId(_InternalId):
    """Alertissimo identity for a record (generated by Portfolio Core)."""


@dataclass(frozen=True)
class InternalExecutionId(_InternalId):
    """Alertissimo identity for one successful physical endpoint execution."""


def new_internal_execution_id() -> InternalExecutionId:
    """Generate an opaque execution ID without implying scientific meaning."""
    return InternalExecutionId(f"exec_{uuid4().hex}")


__all__ = [
    "InternalExecutionId",
    "InternalPortfolioId",
    "InternalRecordId",
    "new_internal_execution_id",
]
