[server]
headless = true

[runner]
magicEnabled = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f8"
textColor = "#172033"
